/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice/speak'
import { Route as ApiPublicOauthGoogleCallbackRouteImport } from './routes/api/public/oauth/google/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthGoogleCallbackRoute =
  ApiPublicOauthGoogleCallbackRouteImport.update({
    id: '/api/public/oauth/google/callback',
    path: '/api/public/oauth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/memory'
    | '/onboarding'
    | '/settings'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/api/public/oauth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/memory'
    | '/onboarding'
    | '/settings'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/api/public/oauth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/memory'
    | '/onboarding'
    | '/settings'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/api/public/oauth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
  ApiPublicOauthGoogleCallbackRoute: typeof ApiPublicOauthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google/callback': {
      id: '/api/public/oauth/google/callback'
      path: '/api/public/oauth/google/callback'
      fullPath: '/api/public/oauth/google/callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
  ApiPublicOauthGoogleCallbackRoute: ApiPublicOauthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
